// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1X0lG5oZPV57Jy1NJSaFal0O3GCBblWo',
    appId: '1:890314411848:android:62260fb764abdad5d62d7d',
    messagingSenderId: '890314411848',
    projectId: 'radianprojies',
    databaseURL: 'https://radianprojies-default-rtdb.firebaseio.com',
    storageBucket: 'radianprojies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBEVokOzfT5CdMyqlPJfHoM2SnukMVsDk',
    appId: '1:890314411848:ios:5658231492c86af4d62d7d',
    messagingSenderId: '890314411848',
    projectId: 'radianprojies',
    databaseURL: 'https://radianprojies-default-rtdb.firebaseio.com',
    storageBucket: 'radianprojies.appspot.com',
    androidClientId: '890314411848-s4qpo84s0scdtgf292i82cm3ol4acb6l.apps.googleusercontent.com',
    iosClientId: '890314411848-hatl2cudnail1j91vq9tcpjd3cnnpmnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.watertrackerapp',
  );
}
